# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=100)),
                ('image_text', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('ingress', models.TextField()),
                ('hoveddel', models.TextField()),
                ('image_mellom', models.TextField(blank=True)),
                ('image_mellomtext', models.TextField(blank=True)),
            ],
        ),
    ]
