# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hoveddel',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_mellom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_mellomtext',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ingress',
        ),
    ]
